config/routes.rb
Drama::Application.routes.draw do
  devise_for :members

  resources :membership_kinds

  root :to => "home#index"

end

app/models/account.rb
class Account

  include DataMapper::Resource

  property :id, Serial
  property :name, String

  has n, :account_entries

  property :deleted_at, ParanoidDateTime
end

app/models/account_entry.rb
class AccountEntry

  include DataMapper::Resource

  property :id, Serial

  property :amount, Decimal
  property :booked_at, DateTime
  property :text, String, :length => 255
  property :created_by, String
  belongs_to :account

end

app/models/member.rb
class Member

  include DataMapper::Resource
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable


  property :id, Serial
  property :nickname, String, :required => true
  property :first_name, String, :required => true
  property :last_name, String, :required => true
  property :is_admin, Boolean, :default => false
  
  property :intern_list_email, String, :length => 255

  property :street, String, :required => true, :length => 150
  property :zip_code, String, :required => true
  property :city, String, :required => true, :length => 150
  property :country, String, :required => true
  property :phone_number, String
  property :day_of_birth, Date
  
  has n, :membership_periods

  property :deleted_at, ParanoidDateTime


  validates_format_of :intern_list_email, :as => :email_address
  
  
  timestamps :at

end

app/models/membership_kind.rb
class MembershipKind

  include DataMapper::Resource

  property :id, Serial

  property :name, String
  property :fee, Decimal, :precision => 10, :scale => 2

end

app/models/membership_period.rb
class MembershipPeriod

  include DataMapper::Resource

  property :id, Serial

  property :begin_date, Date
  property :end_date, Date
  property :fee_override, Decimal

  belongs_to :member
  belongs_to :membership_kind
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/membership_kinds_controller.rb
class MembershipKindsController < ApplicationController
  # GET /membership_kinds
  # GET /membership_kinds.xml
  def index
    @membership_kinds = MembershipKind.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @membership_kinds }
    end
  end

  # GET /membership_kinds/1
  # GET /membership_kinds/1.xml
  def show
    @membership_kind = MembershipKind.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membership_kind }
    end
  end

  # GET /membership_kinds/new
  # GET /membership_kinds/new.xml
  def new
    @membership_kind = MembershipKind.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membership_kind }
    end
  end

  # GET /membership_kinds/1/edit
  def edit
    @membership_kind = MembershipKind.get(params[:id])
  end

  # POST /membership_kinds
  # POST /membership_kinds.xml
  def create
    @membership_kind = MembershipKind.new(params[:membership_kind])

    respond_to do |format|
      if @membership_kind.save
        format.html { redirect_to(@membership_kind, :notice => 'Membership kind was successfully created.') }
        format.xml  { render :xml => @membership_kind, :status => :created, :location => @membership_kind }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membership_kind.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /membership_kinds/1
  # PUT /membership_kinds/1.xml
  def update
    @membership_kind = MembershipKind.get(params[:id])

    respond_to do |format|
      if @membership_kind.update_attributes(params[:membership_kind])
        format.html { redirect_to(@membership_kind, :notice => 'Membership kind was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membership_kind.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /membership_kinds/1
  # DELETE /membership_kinds/1.xml
  def destroy
    @membership_kind = MembershipKind.get(params[:id])
    @membership_kind.destroy

    respond_to do |format|
      format.html { redirect_to(membership_kinds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/membership_kinds_helper.rb
module MembershipKindsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drama</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/membership_kinds/_form.html.haml
= form_for @membership_kind do |f|
  -if @membership_kind.errors.any?
    #error_explanation
      %h2= "#{pluralize(@membership_kind.errors.count, "error")} prohibited this membership_kind from being saved:"
      %ul
        - @membership_kind.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :fee
    = f.text_field :fee

  .actions
    = f.submit 'Save'

app/views/membership_kinds/edit.html.haml
%h1 Editing membership_kind

= render 'form'

= link_to 'Show', @membership_kind
\|
= link_to 'Back', membership_kinds_path

app/views/membership_kinds/index.html.haml
%h1 Listing membership_kinds

%table
  %tr
    %th Name
    %th Fee
    %th
    %th
    %th

  - @membership_kinds.each do |membership_kind|
    %tr
      %td= membership_kind.name
      %td= membership_kind.fee
      %td= link_to 'Show', membership_kind
      %td= link_to 'Edit', edit_membership_kind_path(membership_kind)
      %td= link_to 'Destroy', membership_kind, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Membership kind', new_membership_kind_path

app/views/membership_kinds/new.html.haml
%h1 New membership_kind

= render 'form'

= link_to 'Back', membership_kinds_path

app/views/membership_kinds/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_membership_kind_path(@membership_kind)
\|
= link_to 'Back', membership_kinds_path